export default function Footer() {
  return (
    <footer className="border-t border-zinc-200 bg-white">
      <div className="mx-auto w-full max-w-6xl px-6 py-6 text-xs text-zinc-500">
        Documents generated by Prelegal are drafts only and do not constitute legal advice. Review with a qualified
        attorney before use.
      </div>
    </footer>
  );
}
